name: app_theme_kit
description: A modular Flutter theming kit with light/dark mode, color schemes, text themes, and Material 3 subthemes.
version: 0.0.9
homepage: https://github.com/afesohromeo/app_theme_kit
repository: https://github.com/afesohromeo/app_theme_kit
issue_tracker: https://github.com/afesohromeo/app_theme_kit/issues

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # if you're using Google Fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0 # Optional: static analysis
  flutter_lints: ^6.0.0
