name: flutter_theme_kit
description: A reusable Material 3 theme kit for Flutter apps with custom color schemes, text styles, and spacing constants.
version: 0.0.1
homepage: https://github.com/afesohromeo/flutter_theme_kit
repository: https://github.com/afesohromeo/flutter_theme_kit

environment:
  sdk: '>=3.6.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # if you're using Google Fonts
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0 # Optional: static analysis
  flutter_lints: ^6.0.0
